### PR TITLE
Fix for issue #74

### PR DESCRIPTION
**Pull request by helterscelter**
sort Tag list as a list of version numbers so that
the correct "last" or "most current" tag is picked

### CODE REVIEW

**Comment by Uxorious** [comment]
Works perfectly.
Thanks!

**Comment by rywall** [comment]
I was experiencing #72 and this fixed it for me. Thanks a lot!

**Comment by robinkraft** [comment]
Ditto!

**Comment by helterscelter** [comment]
I'm glad this appears to fix the issue for you folks.  I wonder how we can get this reviewed and pulled?

**Comment by vtkstef** [comment]
thanks it pulled 7u10 without a hitch

**Comment by madmuffin1** [comment]
Using your patch I was able to update to 7u11 without any problems. Without the patch, oab tried building 7u9 over and over

**Comment by skn** [comment]
Was able to download and build 7u11 using this patch. Thanks! I am surprised this has not been pulled in yet.

**Comment by vpassapera** [comment]
This needs to be pulled in!

**Pull request closed without merging**
