### PR TITLE
Fixed a Java6 jce download page

### PR DESCRIPTION
**Pull request by n0ts**
Hi, I fixed java6 jre donwload page.
This pull request is same issue for #107 and #106.

Thank you.

### CODE REVIEW

**Comment by Pneumatus** [comment]
:+1:

**Comment by diversit** [comment]
+1, had to apply this patch to be able to install Java 6.

**Comment by robbymeals** [comment]
+1

**Comment by xiyoulaoyuanjia** [comment]
+1

**Comment by deutrino** [comment]
+1

**Pull request merged**
