### PR TITLE
oab-java6 based pbuilder repo creator

### PR DESCRIPTION
**Pull request by alanfranz**
Hello,
I liked your oab-java6 work very much, but needed a different approach - I wanted to build packages for different distros and let them be installed from an internal (authenticated) repo, and sign it with my own preferred key.

So I modified your scripts to use pbuilder for building; currently works on ubuntu only and builds packages for ubuntu only, but I'd like to add Debian next week.

I had to duplicate oab-java6.sh because I found it hard to make changes without breaking the previous version.

make_jdk_repo.sh contains a basic help, but I've not updated the readme since I'd like to know what you think about it before putting too much effort in it. If you think the projects should just stay separate let me know.

### CODE REVIEW

**Comment by flexiondotorg** [comment]
Hi Alan,

Thanks for contributing!

I'm got to be busy today and over the weekend, but I'll review your changes next week and get back to you. 

Regards, Martin.

**Comment by flexiondotorg** [comment]
Hi Alan,

I see what you are after here. Looks very sensible. If you don't mind I might reject this pull request and start integrating the feature you've proposed into the main script in a slightly different way. Does that sound reasonable?

Regards, Martin.

**Comment by alanfranz** [comment]
Absolutely. My pull proposal is a bit "drafty" because I didn't know what was the best way to integrate it, nor I was sure if it was feasible to.

Feel free to do whatever you think appropriate, and ask for help if you need it. If you need a jabber/skype/msn contact to get in touch just send me a private message.

**Comment by flexiondotorg** [comment]
Hi,

I decided that I will not be integrating these changes, since I am using this script purely for server deployments. Thanks for contributing though :-)

Regards, Martin.

**Comment by alanfranz** [comment]
I am using it for server deployments as well, but using that I don't
need to redownload-and-repackage it on any-and-all servers - some of
which don't have internet access.

No problem though, I'll just keep my fork on github. There seems to be
new life in make-jpkg as well, hence all our efforts may be obsolete in
a short time.

Bye!

**Pull request closed without merging**
