### PR TITLE
Fix 7u51 build

### LINKED ISSUE #123: oab-java.sh (0.3.0) fails in current state
I get the following error in the log:
cp -a x64/jre debian/oracle-java7-bin/usr/lib/jvm/java-7-oracle-1.7.0.51
cp: cannot stat `x64/jre': No such file or directory
make: **\* [binary-oracle-java7-bin] Error 1
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
^H^H8242's retcode: 2
success

And this in standard out:
ERROR! Packages failed to build.

Somebody else filed: https://github.com/rraptorr/oracle-java7/issues/15 against oracle-java7 but they think its an issue here. It seemed like they had to change their format due to changes in dpkg (see comment in link).

For reference I am running the script on vagrant's precise64.box. Any other details, I'd be happy to provide.

### PR DESCRIPTION
**Pull request by ladios**
This should fix #123

### CODE REVIEW

**Comment by ladios** [comment]
Some commands in the upstream's preparing script might fail silently (in my case curl exited with error when resuming the already download completed JCE package), but doesn't affect the build.

**Comment by ykulbak** [comment]
Thanks, this fixed 7u51 for me

**Comment by nifgraup** [comment]
Works.

**Comment by tfnico** [comment]
Thanks! Works for me on Ubuntu 12.04 :thumbsup:

**Comment by shinji257** [comment]
Yup.  Confirmed it fixes it for me as well.  Great job!

**Comment by wlk** [comment]
working for me as well

**Comment by tuxinaut** [comment]
Thanks! Also works for me on Ubuntu 12.04 :thumbsup:

**Comment by rmorgans** [comment]
Cheers - works for me on 13.10 saucy for version 7 (the -7 flag) -> however the version 6 I have the
Unmet build dependencies: lib32asound2 ia32-libs issue (which is unrelated to this I think)

**Comment by ladios** [comment]
@rmorgans That should be #122 which can be fixed by #124
I merged that in my fork's master branch ladios@218eddf0f969d111cc2efdd8f58c08ec2bdd30ab

**Comment by timmc** [comment]
Confirmed on Ubuntu 12.10 Quantal Quetzal. :+1: (For `-7`, at least.)

**Comment by dpursehouse** [comment]
:+1:  Works for me on Ubuntu 12.04 LTS with `-7`

**Comment by dol** [comment]
Thx, working with '-7' on Ubuntu 12.10.

**Comment by ladios** [comment]
Replaced by #130

**Pull request closed without merging**
